config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  authenticated :user do
    root to: "posts#index", as: :authenticated_root
    resources :posts, only: [:index, :show, :create, :destroy]
    resources :comments, only: [:show, :create]
  end

  unauthenticated :user do
    root to: "home#welcome"
  end
end

app/models/blacklist.rb
class Blacklist
  include Mongoid::Document
  field :word, type: String

  validates :word, presence: true, uniqueness: true

  after_save :save_variations
  
  def save_variations
    words = create_variations self.word
    pluralized_words = create_variations self.word.pluralize
    (words+pluralized_words).each do |word|
      Blacklist.create(word: word)
    end
  end

  private

  def create_variations word
    words = []
    
    new_word = word.downcase.gsub(/a|e|i|o|u/) do |m|
      case m.downcase
      when 'a'
        '@'
      when 'e'
        '&'
      when 'i'
        "1"
      when 'o'
        "0"
      when 'u'
        "u"
      end
    end
  
    words << new_word unless words.include? new_word
  
    word.split("").each_with_index do |char,index|
      case char.downcase
      when 'a'
        start = word[0..index].gsub(/a/,"@")
        new_word = start + word[index+1..-1]
      when 'e'
        start = word[0..index].gsub(/e/,"&")
        new_word = start + word[index+1..-1]
      when 'i'
        start = word[0..index].gsub(/i/,"1")
        new_word = start + word[index+1..-1]
      when 'o'
        start = word[0..index].gsub(/o/,"0")
        new_word = start + word[index+1..-1]
      when 'u'
        start = word[0..index].gsub(/u/,"y")
        new_word = start + word[index+1..-1]
      end
      words << new_word unless words.include? new_word
    end
  
    words
  end

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  include Mongoid::Timestamps
  field :comment, type: String

  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/post.rb
class Post
  include Mongoid::Document
  include Mongoid::Timestamps
  field :title, type: String

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  field :name, type: String
  field :nickname, type: String
  field :admin, type: Boolean, default: false

  def will_save_change_to_email?
    false
  end

  has_many :comments, dependent: :destroy
  has_many :posts, dependent: :destroy

  validates_presence_of :name, :nickname
  validates_uniqueness_of :nickname

  before_save :first_user, on: :create

  def first_user
    self.admin = true if User.count == 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
    skip_before_action :verify_authenticity_token
    include Pundit

    private

    def user_not_authorized
        redirect_to request.referrer, flash: {alert: "Unauthorized action"}
    end

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :nickname])
        devise_parameter_sanitizer.permit(:account_update, keys: [:name, :nickname])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_comment, only: [:show]
  before_action :set_commentable, only: [:create]

  def show
    render json: @comments
  end

  def create
    filtered_comment = BlacklistService.new(comment_params[:comment]).perform
    @comment = Comment.new({comment: filtered_comment}.merge(user: current_user, commentable: @commentable))
    if @comment.save
      redirect_to request.referrer, flash: {success: "Comment was successfully created"}
    else
      redirect_to posts_path, flash: {error: "Something went wrong!"}
    end
  end

  private
  
  def set_comment
    @comments = Post.find(params[:id]).comments.order(created_at: :desc)
  end

  def set_commentable
    @commentable = Comment.find(params[:comment_id]) if params[:comment_id]
    @commentable = Post.find(params[:post_id]) if params[:post_id]
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def welcome
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, only: [:show, :destroy]
  before_action :authorize_post, only: [:destroy]

  def index
    @posts = Post.all.order(created_at: :desc).page(params[:page])
    @post = Post.new
  end

  def show
  end

  def create
    filtered_post = BlacklistService.new(post_params[:title]).perform
    @post = Post.new({title: filtered_post}.merge(user: current_user))
    if @post.save
      redirect_to @post, flash: {success: "Post was successfully created"}
    else
      redirect_to posts_path, flash: {error: "Something went wrong!"}
    end
  end

  def destroy
    if @post.delete
      redirect_to posts_url, flash: {success: "Post was successfully destroyed"}
    else
      redirect_to @post, flash: {error: "Something went wrong!"}
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title)
  end

  def authorize_post
    authorize @post
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def format_time(time, format=:long, blank_message="&nbsp;")
    time.blank? ? blank_message : time.to_s(format)
  end
end

app/views/home/welcome.html.erb
<div class="container">
    <% flash.each do |key, value| %>
        <script> M.toast({html: "<%= value %>", classes: "rounded <%= key %>"});</script>
    <% end %>
    <div class="row">

      <div class="col s12 center-align">
        <h3>Welcome to DISCUSSION FORUM.</h3>
        <h5>Create an account or login to an existing one for enjoying the discussion forum developed in Ruby</h5>
        <br><br>
        <%= link_to("Login", new_user_session_path, class: "waves-effect waves-light btn-large") %>
        <%= link_to("Sign Up", new_user_registration_path, class: "waves-effect waves-light btn-large") %>
      </div>

    </div>
        
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RForum</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="row">
    <div class="col s12">
        <%= form_for(@post) do |f| %>
            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <div class="input-field col s6">
                <%= text_field(:post, :title,:class => "validate", :required => true) %>
                <label for="first_name">Thread</label>
            </div>
            <div class="input-field col s6">
                <button class="btn waves-effect waves-light" type="submit" name="commit">Create
                    <i class="material-icons right">send</i>
                </button>
            </div>
        <% end %>
    </div>
  </div>

app/views/posts/_post.html.erb
<div class="col s12 m7">
    <%= link_to post do%>
        <div class="card horizontal grey darken-3">
            <div class="card-stacked">
                <div class="card-content white-text">
                    <p><a><%= post.user.nickname.capitalize %> at <%= post.created_at.strftime("%m/%d/%y, %k:%M") %>:</a> <%= post.title %></p>
                </div>
                <div class="card-action">
                    <a> <%= post.comments.count %> Comments </a>
                    <%= link_to post do %>
                        <i class="material-icons">comment</i>
                    <% end %>
                    <% if post.user == current_user %>
                        <%= link_to post, method: :delete, data: { confirm: 'Are you sure?' } do %>
                            <i class="material-icons right" style="color: #d50000;">delete_forever</i>
                        <% end %>
                    <% end %>
                </div>
            </div>
        </div>
    <%end%>
</div>

app/views/posts/index.html.erb
<div class="container threads">
    <% flash.each do |key, value| %>
        <script> M.toast({html: "<%= value %>", classes: "rounded <%= key %>"});</script>
    <% end %>
    <%= render 'posts/form', task: @post %>
    <%= render @posts %>
    <%= paginate @posts %>
</div>

app/views/posts/show.html.erb
<div class="container post_margim">
    <% flash.each do |key, value| %>
        <script> M.toast({html: "<%= value %>", classes: "rounded <%= key %>"});</script>
    <% end %>
    <div class="col s12 m7">
        <div class="card horizontal grey darken-3">
            <div class="card-stacked">
                <div class="card-content white-text">
                    <p> <a><%= format_time(@post.created_at, :short, "N/A") %> | <%= @post.user.nickname.capitalize %>: </a> <%= @post.title %>
                    <i class="material-icons right" id="button_comment_post">comment</i></p>
                </div>
                <div class="card-action white-text grey darken-3" id="comment_post" hidden>
                    <form class="new_comment" id="new_comment" action="/comments" accept-charset="UTF-8" method="post">
                        <div class="input-field col s6">
                            <%= text_field(:comment, :comment,:class => "validate white-text", :required => true) %>
                            <label for="first_name">Comment</label>
                        </div>
                        <div class="input-field col s6">
                            <button class="btn waves-effect waves-light" type="submit" name="commit">Create
                                <i class="material-icons right">send</i>
                            </button>
                        </div>
                        <div class="input-field col s6" hidden>
                            <input type="hidden" name="post_id" id="post_id" value=<%= @post.id %> >
                        </div>
                    </form>
                </div>
                <div id="all_comments">
                </div>
            </div>
        </div>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            This system was developed as part of the hiring process for Grupo Record Back End Developer position.
        </div>
    </div>
</footer>

app/views/shared/_navbar.html.erb
<nav>
    <div class="nav-wrapper">
        <%= link_to('RForum', root_path, class: "brand-logo center") %>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
            <% if user_signed_in? %>
                <% if current_user.admin?%>
                    <li class="navbar-item"><%= link_to('Admin', rails_admin_path, class: "has-text-white-ter") %></li>
                <% end %>
                <li><%= link_to('Logout', destroy_user_session_path, method: :delete, class: "has-text-white-ter") %></li>
            <% else %>
                <li><%= link_to("Login", new_user_session_path, class: "button is-medium is-outlined is-primary") %></li>
                <li><%= link_to("Sign Up", new_user_registration_path, class: "button is-medium is-outlined is-primary") %></li>
            <% end %>
        </ul>
    </div>
</nav>